services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    environment:
      FOXGLOVE_API_BASE_URL: ${FOXGLOVE_API_BASE_URL:-}
      FOXGLOVE_API_KEY: ${FOXGLOVE_API_KEY:-}
